# Generated by Django 6.0.4 on 2026-04-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='type',
            field=models.CharField(choices=[('PTO', 'Paid Time Off'), ('SICK', 'Sick Leave'), ('HOLIDAY', 'Public Holiday'), ('OTHER', 'Other')], default='PTO', max_length=20),
        ),
    ]
