# Generated by Django 6.0.4 on 2026-04-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_vacation_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('shift', 'user', 'type')},
        ),
    ]
