# Generated by Django 6.0.4 on 2026-04-26 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_alter_assignment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usertechnology',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('shift', 'user', 'type'), name='unique_assignment_shift_user_type'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('date', 'technology'), name='unique_shift_date_technology'),
        ),
        migrations.AddConstraint(
            model_name='usertechnology',
            constraint=models.UniqueConstraint(fields=('user', 'technology'), name='unique_user_technology'),
        ),
    ]
