# Generated by Django 6.0.4 on 2026-04-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_sitesettings'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='standbydetail',
            name='shift',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standby_details', to='calendar_app.shift'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='standbydetail',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'PRIMARY')), fields=('shift', 'role'), name='unique_primary_standby_per_shift'),
        ),
    ]
