# Generated by Django 6.0.4 on 2026-04-27 20:26

from django.db import migrations

import calendar_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_alter_customuser_managers_standbydetail_shift_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', calendar_app.models.CustomUserManager()),
            ],
        ),
    ]
