# Generated by Django 6.0.4 on 2026-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='anon_throttle_rate',
            field=models.CharField(default='100/day', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='jwt_access_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='jwt_refresh_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='user_throttle_rate',
            field=models.CharField(default='1000/hour', max_length=20),
        ),
    ]
