# Generated by Django 6.0.4 on 2026-04-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('calendar_app', '0008_sitesettings_anon_throttle_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='role',
            field=models.CharField(choices=[('CR', 'Read-Only'), ('SIAE', 'Client Domain'), ('ENG', 'Consultant Domain')], default='CR', max_length=10),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['type'], name='calendar_ap_type_8450f3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['shift', 'type'], name='calendar_ap_shift_i_150b61_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='calendar_ap_role_fc55ea_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date'], name='calendar_ap_date_5b85ac_idx'),
        ),
    ]
