# Generated by Django 6.0.4 on 2026-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_technology_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_color',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green')], default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
