# Generated by Django 5.1.15 on 2026-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_sitesettings_announcement_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_backend',
            field=models.CharField(choices=[('smtp', 'SMTP (External)'), ('postfix', 'Postfix (Local)')], default='smtp', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postfix_host',
            field=models.CharField(default='host.docker.internal', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postfix_port',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='standbydetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertechnology',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
