# Generated by Django 5.1.15 on 2026-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0013_sitesettings_client_email_alter_assignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_template_body',
            field=models.TextField(blank=True, default='', help_text='HTML email body. Use {first_name}, {last_name}, {technology}, {vacation_type}, {start_date}, {end_date}, {brand_name} as placeholders.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_template_enabled',
            field=models.BooleanField(default=False, help_text='Use custom email template instead of default'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_template_subject',
            field=models.CharField(blank=True, default='[{brand_name}] Consultant Vacation Notification: {first_name} {last_name}', max_length=255),
        ),
    ]
