# Generated by Django 5.1.15 on 2026-05-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0014_sitesettings_email_template_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='test_email_recipient',
            field=models.EmailField(blank=True, help_text='Email address to send test emails to', max_length=254, null=True),
        ),
    ]
